version: "3.9"

services:
  postgres:
    image: postgres:16.2
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.5
    container_name: keycloak
    restart: unless-stopped
    command: ["start"]
    depends_on:
      - postgres
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8090
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8090:8080"
    networks:
      - keycloak_network

  service-keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-keycloak
    restart: unless-stopped
    depends_on:
      - keycloak

    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_URL: http://host.docker.internal:8761/eureka/

      # Keycloak remoto/local
      KEYCLOAK_ISSUER_URI: ${KEYCLOAK_ISSUER_URI}
      KEYCLOAK_JWK_SET_URI: ${KEYCLOAK_JWK_SET_URI}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_USER_CONSOLE: ${KEYCLOAK_USER_CONSOLE}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_SERVER_URL: ${KEYCLOAK_SERVER_URL}
      KEYCLOAK_REALM_NAME: ${KEYCLOAK_REALM_NAME}
      KEYCLOAK_REALM_MASTER: ${KEYCLOAK_REALM_MASTER}
      PRINCIPLE_ATTRIBUTE: ${PRINCIPLE_ATTRIBUTE}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      RESOURCE_ID: ${RESOURCE_ID}
      JWT_TOKEN_URL: ${JWT_TOKEN_URL}
      JWT_PUBLIC_KEY: ${JWT_PUBLIC_KEY}

      # Mail
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}

      # Recovery
      RECOVERY_FRONTEND_URL: ${RECOVERY_FRONTEND_URL}
      RECOVERY_TTL_SECONDS: ${RECOVERY_TTL_SECONDS}
      SERVER_PORT: 8081
      EUREKA_INSTANCE_NON_SECURE_PORT: 8081
    ports:
      - "8081:8081"
    networks:
      - keycloak_network

volumes:
  postgres_data:

networks:
  keycloak_network:
    driver: bridge